apiVersion: v1
kind: Service
metadata:
  name: mysql-cuentas
  namespace: cooperativa
spec:
  selector:
    app: mysql-cuentas
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-socios
  namespace: cooperativa
spec:
  selector:
    app: postgres-socios
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: microservicio-cuentas
  namespace: cooperativa
spec:
  selector:
    app: microservicio-cuentas
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: socios
  namespace: cooperativa
spec:
  selector:
    app: socios
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cooperativa
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
